# Generated by Django 5.1.3 on 2024-12-05 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='salary',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(default='Something', max_length=100),
        ),
    ]
