# Generated by Django 5.1.3 on 2024-12-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_expense_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Shopping', 'Shopping'), ('Transport', 'Transport'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
